[project]
name = "pdf2md"
version = "0.2.0"
description = "Convert PDF to Markdown using PaddleOCR"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy",
    "paddleocr",
    "paddlepaddle",
    "pillow",
    "pymupdf",
    "setuptools",
]
